### ISSUE TITLE
Failed to build android on 4.0.1

### ISSUE THREAD

**Issue by itaishalom** [authpass/biometric_storage#55] opened 2022-01-23 17:57 UTC
![Screenshot_20220123-195527](https://user-images.githubusercontent.com/9066121/150691474-a5bb12a8-021b-4efc-9147-3a06acb28758.png)

So you know what this is?

**Comment by hpoul** [comment] 2022-01-23 18:16
Seems related to #54 - Maybe you can try upgrading Kotlin to 1.6 (or downgrading to the previous plugin version) and see if this resolves the problem for you?

**Comment by itaishalom** [comment] 2022-01-23 18:36
Thanks for reply, I'll check

**Comment by itaishalom** [comment] 2022-01-23 20:35
Still getting it:
Execution failed for task ':biometric_storage:kaptGenerateStubsReleaseKotlin'.
> Could not resolve all files for configuration ':biometric_storage:releaseCompileClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes ***artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm***.
      > Execution failed for JetifyTransform: /Users/appdev/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/appdev/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).


i have:
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip
and


dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"

and

  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10"

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.firebase.crashlytics'


Have I forgot something?

**Comment by hpoul** [comment] 2022-01-23 20:49
I think you are using an old jdk, can you try with hands>=16?

**Comment by itaishalom** [comment] 2022-01-23 21:15
Where can I set it? (Long time on flutter, forgot android :/)

**Comment by hpoul** [comment] 2022-01-23 21:21
depends how you are building it.. it looks like a CI .. so you have to make sure that your base image as some current java version running..
if you are building on android studio you can choose so in the gradle build configuration.. https://stackoverflow.com/a/64220088/109219

**Comment by itaishalom** [comment] 2022-01-23 21:24
You are correct! I'll check it

**Comment by itaishalom** [comment] 2022-01-24 07:15
I tried with jdk 17 but the issue remains

**Comment by hpoul** [comment] 2022-01-24 08:57
are you sure you are using the right jdk? and it's the same error message?
In your previous log it states "Unsupported class file major version 60." which imho can't happen with jdk 17 🤨

**Comment by killalad** [comment] 2022-01-27 16:59
Hi, the bump-up of the java to 16+ worked, however then there was another issue which was throwing this biometric storage library, caused by kotlin internal "something" (I'm not android dev:D) which was then resolved increasing the kotlin version to 1.6.10.  

Also, @itaishalom beware that using Gradle 7.0 you cannot use Java 17 (https://docs.gradle.org/current/userguide/compatibility.html). 🙂

**Comment by Ahmadre** [comment] 2022-01-29 01:00
Same issue, but we cannot upgrade jdk due to other dependencies. Can't we check for actual kotlin version in build.gradle? If-statements exists in Android configs and we would have these errors for apps that cannot upgrade. This should have been checke in https://github.com/authpass/biometric_storage/pull/54 before merging.

**Comment by hpoul** [comment] 2022-01-29 11:27
@Ahmadre feel free to use the old plugin version, or create a PR

**Comment by tahitiangabriel** [comment] 2022-02-11 23:32
I've used this workaround : https://github.com/authpass/biometric_storage/issues/53#issuecomment-1027721157

**Comment by YazeedAlKhalaf** [comment] 2022-02-25 15:30
i have some input regarding the #54 upgrade.
i upgraded my project to the latest stable flutter as of today 2.10.2.
now the default Koltin version that flutter projects use for android is `1.6.10`.

`biometric_storage` still says `1.5.21` here:
https://github.com/authpass/biometric_storage/blob/master/android/build.gradle#L5

maybe this is the problem

**Comment by hpoul** [comment] 2022-04-05 19:56
Please see #58 should be fixed in 4.1.0

**Closed by hpoul** 2022-04-05 19:56 UTC
