### ISSUE TITLE
Compiling on linux fails

### ISSUE THREAD

**Issue by miDeb** [authpass/biometric_storage#42] opened 2021-10-05 20:00 UTC
Compiling an app that depends on `biometric_storage` fails on the latest ~~master channel~~ stable release with the following error message (on linux and I'd guess on macos as well):
```plaintext
dart_tool/flutter_build/generated_main.dart:47:9: Error: Undefined name 'Win32BiometricStoragePlugin'.
        Win32BiometricStoragePlugin.registerWith();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I think this might be related to recent changes to `dartPluginClass` by flutter, so if you think this is flutter's bug and not yours feel free to close this issue :)

**Comment by nikhilbadyal** [comment] 2021-12-04 05:44
Same issue. Unable to compile because `Win32BiometricStoragePlugin.registerWith();` is undefined.

**Comment by Samin-youki** [comment] 2021-12-09 14:31
@hpoul  any update on this?

**Comment by TMSantos** [comment] 2021-12-09 16:07
@miDeb did you found any solution?

**Comment by miDeb** [comment] 2021-12-09 17:07
@TMSantos sorry, I did not.

**Comment by brianblanchard-wf** [comment] 2021-12-09 17:51
I took a stab a fixing this in https://github.com/authpass/biometric_storage/pull/47. There is more info around the source of the issue. It is not just a linux issue, this issue most likely reproduces on any platform.

If you all have the time to target my branch as your dependency of `biometric_storage` I would love to know if this fixes the issues you are seeing 😄

**Comment by TMSantos** [comment] 2021-12-10 08:15
@brianblanchard-wf thanks, Indeed it happens outside linux, I use macOS, I end up forking and removing desktop part https://github.com/TMSantos/biometric_storage/commit/ce730be728b2710c7a6644863fc305a68b7b71c6 , as I only need mobile, will wait for this to be merged

**Comment by hpoul** [comment] 2021-12-10 16:52
I've published #47 as `4.0.0-rc.1` - maybe you could give it a try and let me know if it works for you. thanks.

**Comment by nikhilbadyal** [comment] 2021-12-10 19:09
@hpoul  Thanks, fixed now.

**Comment by miDeb** [comment] 2021-12-10 23:32
Works for me - thanks!

**Comment by itaishalom** [comment] 2021-12-14 11:02
Solved my issue.

**Comment by Samin-youki** [comment] 2021-12-16 07:27
I'm running my app on windows, with flutter 2.8.0 and dart 2.15.0 and getting this error...
any solution?

**Comment by Samin-youki** [comment] 2021-12-16 07:38
@hpoul i could not test the version you published:

`biometric_storage ^4.0.0-rc.1 which doesn't match any versions, version solving failed.`

**Comment by hpoul** [comment] 2021-12-16 07:59
@Samin-youki sorry, i called it `4.0.0-dev.1` 🙈 https://pub.dev/packages/biometric_storage/versions/4.0.0-dev.1

**Comment by Samin-youki** [comment] 2021-12-16 08:54
@hpoul thank you so much, the problem is fixed in `4.0.0-dev.1` :)

**Comment by Ahmadre** [comment] 2021-12-16 17:37
@hpoul 4.0.0-dev.1 is not working for Web anymore!!!!! Why isn't this tested on every platform????

**Comment by Ahmadre** [comment] 2021-12-16 17:38
Why isn't this a federated plugin? win32 is always crashing our apps!

**Comment by hpoul** [comment] 2021-12-16 17:42
> @hpoul 4.0.0-dev.1 is not working for Web anymore!!!!! Why isn't this tested on every platform????

Okay, I'll refund you your money 🤣
Feel free to create a PR with your tests, but keep your!!!!!????!!!! To yourself. Thanks!!!!

**Comment by Ahmadre** [comment] 2021-12-17 18:44
ci/cd pipeline it not working:

```
Xcode's output:
↳
    /Users/vagrant/git/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'biometric_storage' not found
    @import biometric_storage;
     ~~~~~~~^~~~~~~~~~~~~~~~~
```

downgrading to v. 2 is also not possible to other build errors.

**Comment by mtskf** [comment] 2022-01-05 01:09
Same error here... 

> ```
> Xcode's output:
> ↳
>     /Users/vagrant/git/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'biometric_storage' not found
>     @import biometric_storage;
>      ~~~~~~~^~~~~~~~~~~~~~~~~
> ```
> 
> downgrading to v. 2 is also not possible to other build errors.

**Comment by wal33d006** [comment] 2022-01-11 06:47
Exact same error here. Flutter version `2.8.1`

**Comment by Ahmadre** [comment] 2022-01-18 16:40
@hpoul do you believe me now?

**Comment by Ahmadre** [comment] 2022-01-18 16:40
@hpoul  https://github.com/authpass/biometric_storage/issues/52

**Comment by mtskf** [comment] 2022-01-18 21:18
I had the same issue but it was sorted after reinstalling pod files somehow:

❯ cd ios
❯ rm Podfile.lock
❯ pod update
❯ pod rm -rf ~/Library/Developer/Xcode/DerivedData/*
❯ flutter clean
❯ flutter pub get
❯ flutter build ios
❯ pod install

**Comment by Ahmadre** [comment] 2022-02-02 07:26
For anyone who's still struggling: https://github.com/flutter/flutter/issues/54599#issuecomment-617244516

This solved my issues

**Comment by hpoul** [comment] 2022-06-16 06:55
I think this should be solved. If anyone still experiences this, please create a new issue.

**Closed by hpoul** 2022-06-16 06:55 UTC
